/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:7559c70d-219c-476d-a65e-8e50e9c376f9",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_E6u78W8Nt",
    "aws_user_pools_web_client_id": "2k8cnmr28f4b1alrg9i0gnlh74",
    "oauth": {},
    "predictions": {
        "identify": {
            "identifyText": {
                "proxy": false,
                "region": "us-west-2",
                "defaults": {
                    "format": "ALL"
                }
            }
        }
    }
};


export default awsmobile;
